empty = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
]
tutorial = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                   e    ",
    "                                        ",
    "                              xxxxxxxx  ",
    "                    xxxxxxx             ",
    "         xxxxxxx                        ",
    "    o                                   ",
    "                                        ",
]
stairs1 = [
    "                                        ",
    "                                        ",
    "                              e         ",
    "                                        ",
    "             xxxxxxxxxxxxxxxxxxxx       ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
    "             xxxxxxxx                   ",
    "                        xxxxxxxxx       ",
    "                                        ",
    "      o      xxxxxxxxx                  ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
]

stairs2 = [
    "                                        ",
    "                                        ",
    "               e                        ",
    "                                        ",
    "             xxxxxxxxxxxxxxxx           ",
    "                                        ",
    "                               xxxxx    ",
    "                                        ",
    "                    xxxxxxxx            ",
    "                                        ",
    "      xxxxxxxxx                         ",
    "                               o        ",
    "                  xxxxxx                ",
    "                           xxxxxxxx     ",
    "                                        ",
]

end = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "      o                                 ",
    "                                        ",
    "                                        ",
]
levels = {
    1: {"format": tutorial},
    2: {"format": stairs1},
    3: {"format": stairs2},
    4: {"format": end},
}
