empty = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
]
# 40 x 20 , 800 x 600, 1 = 20, 1 = 30
level0 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "             xxxxxxxxxxxxxxxxxxxx       ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
    "             xxxxxxxx                   ",
    "                                        ",
    "                        xxxxxxxxx       ",
    "                                        ",
    "      o      xxxxxxxxx                  ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
]
