empty = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
]
# 40 x 15 , 800 x 600, 1 = 20, 1 = 30
tutorial = [
    "                                        ",
    "                              e         ",
    "                                        ",
    "             xxxxxxxxxxxxxxxxxxxx       ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
    "             xxxxxxxx                   ",
    "                                        ",
    "                        xxxxxxxxx       ",
    "                                        ",
    "      o      xxxxxxxxx                  ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
]

stairs = [
    "                                        ",
    "                                        ",
    "               e                        ",
    "                                        ",
    "             xxxxxxxxxxxxxxxx           ",
    "                                        ",
    "                               xxxxx    ",
    "                                        ",
    "                    xxxxxxxx            ",
    "                                        ",
    "      xxxxxxxxx                         ",
    "                               o        ",
    "                  xxxxxx                ",
    "                           xxxxxxxx     ",
    "                                        ",
]
