empty = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
]
tutorial = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                   e    ",
    "                                        ",
    "                              xxxxxxxx  ",
    "                    xxxxxxx             ",
    "         xxxxxxx                        ",
    "    o                                   ",
    "                                        ",
]
stairs1 = [
    "                                        ",
    "                                        ",
    "                              e         ",
    "                                        ",
    "             xxxxxxxxxxxxxxxxxxxx       ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
    "             xxxxxxxx                   ",
    "                        xxxxxxxxx       ",
    "                                        ",
    "      o      xxxxxxxxx                  ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
]

stairs2 = [
    "                                        ",
    "                                        ",
    "               e                        ",
    "                                        ",
    "             xxxxxxxxxxxxxxxx           ",
    "                                        ",
    "                               xxxxx    ",
    "                                        ",
    "                    xxxxxxxx            ",
    "                                        ",
    "      xxxxxxxxx                         ",
    "                               o        ",
    "                  xxxxxx                ",
    "                           xxxxxxxx     ",
    "                                        ",
]

jump1 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                  e                     ",
    "                                        ",
    "               xxxxxxxxx                ",
    "                                        ",
    "                          xxxx          ",
    "                                        ",
    "      xxxxxxxxxx            xxxxxxxxxxxx",
    "                                        ",
    "   xxxxx                                ",
    "                          o             ",
    "          xxxxx                         ",
    "                                        ",
]
jump2 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                             e          ",
    "                                        ",
    "                       xxxxxxxxxxx      ",
    "                                        ",
    "     xxxxxxxxxxx                        ",
    "                                        ",
    "                       xxxxxxxxxxx      ",
    "                                        ",
    "     xxxxxxxxxxx             o          ",
    "                                        ",
    "                                        ",
]
end = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "      o                                 ",
    "                                        ",
    "                                        ",
]
levels = {
    1: {"format": tutorial},
    2: {"format": stairs1},
    3: {"format": stairs2},
    4: {"format": jump1},
    5: {"format": jump2},
    6: {"format": end},
}
