empty = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
]
tutorial = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                   e    ",
    "                                        ",
    "                              xxxxxxxx  ",
    "                    xxxxxxx             ",
    "    o    xxxxxxx                        ",
    "                                        ",
    "                                        ",
]
stairs1 = [
    "                                        ",
    "                                        ",
    "                              e         ",
    "                                        ",
    "             xxxxxxxxxxxxxxxxxxxx       ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
    "             xxxxxxxx                   ",
    "                          xxxxxxx       ",
    "                                        ",
    "      o      xxxxxxxxx                  ",
    "                                        ",
    "    xxxxxx                              ",
    "                                        ",
]
stairs2 = [
    "                                        ",
    "                                        ",
    "               e                        ",
    "                                        ",
    "             xxxxxxxxxxxxxx             ",
    "                                        ",
    "                               xxxxx    ",
    "                                        ",
    "                     xxxxxxx            ",
    "                                        ",
    "      xxxxxxxxx                         ",
    "                               o        ",
    "                  xxxxxx                ",
    "                           xxxxxxxx     ",
    "                                        ",
]
jump1 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                  e                     ",
    "                                        ",
    "               xxxxxxxxx                ",
    "                                        ",
    "                       xxxxxxx          ",
    "                                        ",
    "      xxxxxxxxxx            xxxxxxxxxxxx",
    "                                        ",
    "    xxxxxx                              ",
    "                          o             ",
    "          xxxxx                         ",
    "                                        ",
]
jump2 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                             e          ",
    "                                        ",
    "                       xxxxxxxxxxx      ",
    "                                        ",
    "     xxxxxxxxxxx                        ",
    "                                        ",
    "                       xxxxxxxxxxx      ",
    "                                        ",
    "     xxxxxxxxxxx             o          ",
    "                                        ",
    "                                        ",
]
jump3 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                   e                    ",
    "                                        ",
    "                 xxxxxxxxxxxxx          ",
    "                                        ",
    "                                  xxxxxx",
    "                                        ",
    "    xxxxxxxxxxx            xxxxxx       ",
    "                                        ",
    "xxxx                                    ",
    "                             o          ",
    "    xxxx                                ",
    "                                        ",
]
runup1 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "  e                                     ",
    "                                        ",
    "                                        ",
    "                                        ",
    "xxxxx                                   ",
    "               xx                       ",
    "                         xxxxxxxxxxxxxxx",
    "                                        ",
    "                    xxxxxxxxxxxxxxxxxxxx",
    "   o         xxxxx                      ",
    "      xxxxx                             ",
    "                                        ",
]
runup2 = [
    "                                        ",
    "                 e                      ",
    "                                        ",
    "          xxxxxxxxxxxxxxxx          xxxx",
    "                                        ",
    "                                 xxxxxxx",
    "     o                    xx            ",
    "                xx                      ",
    "    xxxx                                ",
    "                                        ",
    "xx                                      ",
    "                                        ",
    "    xxxx                                ",
    "                                        ",
    "                                        ",
]
climb1 = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "xxxxxxxxxxxx                            ",
    "                                        ",
    "        xxxx                      e     ",
    "                                        ",
    "xxxx                           xxxxx    ",
    "                                        ",
    "        xxxx                      o     ",
    "                                        ",
    "                                        ",
]
stop1 = [
    "                                        ",
    "                                        ",
    "                   e                    ",
    "                                        ",
    "                xxxxxxxx                ",
    "                                        ",
    "     xxx                                ",
    "                                        ",
    "                xxxxxxxx                ",
    "                                        ",
    "               o                xxx     ",
    "                                        ",
    "                xxxxxxxx                ",
    "                                        ",
    "                                        ",
]
stop2 = [
    "                                        ",
    "                                        ",
    "           o                            ",
    "                                        ",
    "                                        ",
    "          xxxxxx                        ",
    "                                        ",
    "                                        ",
    "            e                           ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
]
end = [
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "                                        ",
    "      o                                 ",
    "                                        ",
    "                                        ",
]
